name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: test run
      run: ./main > test.out
    - name: check test results
      run: |
        TEST_RES=$(tail -16 test.out | grep true | wc -l)

        if [ $TEST_RES = 16 ];
          echo "Test passed"
        else
          echo "Test failed"
          exit 1
        fi
